In [1]:
import torch;

In [2]:
torch.__version__

'2.5.1+cu124'

## Q1

In [3]:
tensor = torch.arange(12)
print(tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [4]:
# Reshape
reshaped_tensor = tensor.reshape(2, 6)
print(reshaped_tensor)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


In [5]:
# View
viewed_tensor = tensor.view(3, 4)
print(viewed_tensor)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [6]:
tensor1 = torch.tensor([1, 2])
tensor2 = torch.tensor([3, 4])

# Stack along a new dimension (dim=0)
stacked_tensor = torch.stack((tensor1, tensor2), dim=0)
print(stacked_tensor)

tensor([[1, 2],
        [3, 4]])


In [7]:
tensor = torch.tensor([[[1, 2, 3]]])

# Squeeze the tensor to remove dimensions of size 1
squeezed_tensor = tensor.squeeze()
print(squeezed_tensor)

tensor([1, 2, 3])


In [8]:
tensor = torch.tensor([1, 2, 3])

# Unsqueeze to add a dimension at position 0
unsqueezed_tensor = tensor.unsqueeze(0)
print(unsqueezed_tensor)

tensor([[1, 2, 3]])


## Q2

In [9]:
tensor = torch.arange(7).reshape(1, 7)
print(f"{tensor}\n")

permuted_tensor = tensor.permute(1, 0)

print(f"{permuted_tensor.shape}\n")
print(permuted_tensor)

tensor([[0, 1, 2, 3, 4, 5, 6]])

torch.Size([7, 1])

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]])


## Q3

In [10]:
tensor_ = torch.tensor([[[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]],

                       [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]])

element = tensor_[0, 1, 2]
print(element)

tensor(7)


## Q4

In [11]:
import numpy as np

np_array = np.random.rand(3, 3)
tensor_from_np = torch.from_numpy(np_array)
np_from_tensor = tensor_from_np.numpy()

print("Original NumPy array:\n", np_array)
print("Tensor from NumPy array:\n", tensor_from_np)
print("NumPy array from Tensor:\n", np_from_tensor)

Original NumPy array:
 [[0.79972391 0.49540462 0.19324823]
 [0.2644638  0.7857849  0.40520175]
 [0.83930105 0.58667888 0.68427082]]
Tensor from NumPy array:
 tensor([[0.7997, 0.4954, 0.1932],
        [0.2645, 0.7858, 0.4052],
        [0.8393, 0.5867, 0.6843]], dtype=torch.float64)
NumPy array from Tensor:
 [[0.79972391 0.49540462 0.19324823]
 [0.2644638  0.7857849  0.40520175]
 [0.83930105 0.58667888 0.68427082]]


## Q5

In [12]:
# Create a random tensor with shape (7, 7)
random_tensor = torch.rand(7, 7)
print("Random Tensor (7, 7):\n", random_tensor)

Random Tensor (7, 7):
 tensor([[0.3123, 0.5186, 0.2113, 0.2184, 0.3696, 0.7581, 0.9415],
        [0.7444, 0.4666, 0.7738, 0.7491, 0.4855, 0.6206, 0.1598],
        [0.4120, 0.4138, 0.5935, 0.5760, 0.0856, 0.5895, 0.4988],
        [0.4898, 0.5289, 0.1726, 0.9905, 0.6388, 0.4384, 0.8039],
        [0.0093, 0.3720, 0.6285, 0.1590, 0.1119, 0.6239, 0.7313],
        [0.2506, 0.6282, 0.7492, 0.2489, 0.9606, 0.5490, 0.1329],
        [0.0913, 0.7610, 0.0556, 0.8157, 0.3790, 0.5291, 0.3262]])


## Q6

In [13]:
# Create two random tensors 
tensor_a = torch.randint(1, 11, (1, 7)) 

# Perform matrix multiplication
result = torch.matmul(tensor_a, permuted_tensor)
print("Matrix multiplication result:\n", result)


Matrix multiplication result:
 tensor([[142]])


## Q7

In [14]:
# Check if CUDA is available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cpu


/home/student/Documents/220962038/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


In [15]:
# Create two random tensors
tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(3, 2)

# Move the tensors to the GPU
tensor_1_gpu = tensor_1.to(device)
tensor_2_gpu = tensor_2.to(device)

print("Tensor C on GPU:\n", tensor_1_gpu)
print("Tensor D on GPU:\n", tensor_2_gpu)

print(f"Multiplication result : {torch.matmul(tensor_1_gpu, tensor_2_gpu)}")

Tensor C on GPU:
 tensor([[0.5551, 0.5789, 0.0273],
        [0.8860, 0.9711, 0.5386]])
Tensor D on GPU:
 tensor([[0.6686, 0.2867],
        [0.8445, 0.6743],
        [0.4145, 0.7265]])
Multiplication result : tensor([[0.8713, 0.5693],
        [1.6357, 1.3000]])


In [16]:
torch.cuda.is_available()

False

## Q8

In [17]:
res = torch.matmul(result, tensor_a)
print(res)

tensor([[ 426,  284,  142, 1420,  568, 1420,  994]])


## Q9 & Q10

In [18]:
tensor = torch.rand(5, 5)

max_value = tensor.max()
min_value = tensor.min()

max_value_index = tensor.argmax()  # Index of max value in flattened tensor
min_value_index = tensor.argmin()  # Index of min value in flattened tensor

print(f"Max Value: {max_value}, Max Index: {max_value_index}")
print(f"Min Value: {min_value}, Min Index: {min_value_index}")

Max Value: 0.9951467514038086, Max Index: 6
Min Value: 0.009990870952606201, Min Index: 20


## Q11

In [19]:
torch.manual_seed(7)

random_tensor = torch.rand(1, 1, 1, 10)

squeezed_tensor = random_tensor.squeeze()

print("Original tensor shape:", random_tensor.shape)
print("Squeezed tensor shape:", squeezed_tensor.shape)
print("\nRandom tensor values:\n", random_tensor)
print("\nSqueezed tensor values:\n", squeezed_tensor)

Original tensor shape: torch.Size([1, 1, 1, 10])
Squeezed tensor shape: torch.Size([10])

Random tensor values:
 tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])

Squeezed tensor values:
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
